"""0004 Author + lastname correction

Revision ID: 67d4ff9203ec
Revises: ed17cb629583
Create Date: 2025-03-25 18:32:41.479449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d4ff9203ec'
down_revision = 'ed17cb629583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_index('ix_authors_lastname')
        batch_op.create_index(batch_op.f('ix_authors_lastname'), ['lastname'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authors_lastname'))
        batch_op.create_index('ix_authors_lastname', ['lastname'], unique=1)

    # ### end Alembic commands ###
