"""0004 lastname_modified

Revision ID: d32d6a7d7bd2
Revises: ed17cb629583
Create Date: 2025-03-26 11:05:06.509226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd32d6a7d7bd2'
down_revision = 'ed17cb629583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_index('ix_authors_lastname')
        batch_op.create_index(batch_op.f('ix_authors_lastname'), ['lastname'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authors_lastname'))
        batch_op.create_index('ix_authors_lastname', ['lastname'], unique=1)

    # ### end Alembic commands ###
