"""0003 Author + lastname

Revision ID: ed17cb629583
Revises: a3d746c6b636
Create Date: 2025-03-25 18:18:16.952437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed17cb629583'
down_revision = 'a3d746c6b636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_authors_lastname'), ['lastname'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authors_lastname'))
        batch_op.drop_column('lastname')

    # ### end Alembic commands ###
